# -*- coding: utf-8 -*-
"""Exercise2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1514Z-XOMWPIZB9hQpGldmikqRP8z_om-

#Beneford law test

1. First open file from google drive
"""

from google.colab import files
file = open('/content/drive/MyDrive/ITEC 4700/GME_stock.csv')
text = file.read()

"""2. Split the lines"""

sample = text.split("\n")
print(sample)

"""3. Select from the first row"""

counter = {}
for line in sample[1:]:
  cols = line.split(",")
  if len(cols) > 1:
    first_char = cols[1][0] # the first char of the 1st coloumn
    if first_char in counter:
      counter[first_char] += 1
    else:
      counter[first_char] = 1

"""4. Count the first char of each number"""

for num in ["1","2","3","4","5","6","7","8","9"]:
  if num in counter:
    print(num, counter[num])

"""#Highest Point of Each State Plot Code"""

import matplotlib.pyplot as plt
import urllib.request
u = urllib.request.urlopen("https://github.com/ProfHan/ITEC4700/blob/main/States.csv")
data = u.read().decode('utf-8')
lines = data.split('\n')

states = []
heights = []

for line in lines:
  cols = line.split(",")
  states.append(cols[0])
  heights.append(int(cols[2]))

print(states)
print(heights)

plt.li(states, heights)
plt.xlabel("Heightest Peaks in Feet")
plt.ylabel("American States")
plt.title("Highest points in America")
plt.rcParams['figure.figsize'] = [10, 15]
plt.show()

"""#

#Latitude and Longitude of Each State
"""

import pandas as pd
df = pd.read_csv("https://github.com/ProfHan/ITEC4700/blob/main/Highpoints.csv")
df.head()
plt.scatter(df.longitude, df.latitude)

for x in range(len(df.longitude)):
  plt.annotate(df.name[x],(df.longitude[x],df.latitude[x]),ha="center")