# -*- coding: utf-8 -*-
"""Feb_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtLfzNlulKyJNM20egG5enbM9KJbTcOY

#Regression with our numbers
"""

import matplotlib.pyplot as plt
age = [1,2,3,4,5]
weight = [2,3,4,5,6]
plt.title("Linear Regression")
plt.grid()
plt.scatter(age, weight)
plt.xlabel("age")
plt.ylabel("weight")
plt.show()

"""#Finding Linear Regression Dataset and Making a Graph

Calling data from Google Drive
"""

from google.colab import files
file = open('/content/drive/MyDrive/ITEC 4700/Salary_Data.csv')
text = file.read()
sample = text.split("\n")
print(sample)

experience = []
salary = []

for line in sample:
  cols = line.split(",")
  if len(cols) > 1:
    experience.append(cols[0])
    salary.append(cols[1])

print(experience)
print(salary)

plt.title("Linear Regression")
plt.grid()
plt.scatter(experience, salary)
plt.xlabel("experience")
plt.ylabel("salary")
plt.rcParams['figure.figsize'] = [10,6]
plt.show()

"""Calling data from GitHub URL"""

import urllib.request
u = urllib.request.urlopen("https://github.com/Shianne1/Artificial_Intelligence_Course/blob/main/Python1/GeorgiaByCounty.csv")
data = u.read().decode('utf-8')
lines = data.split('\n')
print(len(lines))