# -*- coding: utf-8 -*-
"""Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxdpUR6i6M2R0tY5ItKGoG0vM8Q0wPSL

# Benfords's Law on County's Population

Could not get the url to work
"""

import urllib.request
u = urllib.request.urlopen("https://github.com/Shianne1/Artificial_Intelligence_Course/blob/main/Python1/GeorgiaByCounty.csv")
data = u.read().decode('utf-8')
lines = data.split('\n')
print(len(lines))

"""This is the start of the actual assignment"""

from google.colab import files
file = open('/content/drive/MyDrive/ITEC 4700/GeorgiaByCounty.csv')
text = file.read()
sample = text.split("\n")
print(sample)

counter = {}
for line in sample[3:]: # this is going through the rows of the csv file
  line = line.replace('"', '').replace("'", '')
  cols = line.split(",")
  if len(cols) > 1:

    first_char = cols[5][0] # the first char of the  6th coloumn

    if first_char in counter:
      counter[first_char] += 1
    else:
      counter[first_char] = 1

for num in ["0","1","2","3","4","5","6","7","8","9"]:
  if num in counter:
    print(num, counter[num])

"""Goergia's County population does some what follow Benford's Law where the lower numbers like 1 & 2 have a higher frenquency that 8 & 9."""