# -*- coding: utf-8 -*-
"""happiness.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8Wfy68VPP4PRDOiw85vyKN43h-Dc77d

## Hppiness and Linear Regression

Here is the link for the Happy data:  https://raw.githubusercontent.com/ProfHan/ITEC4700/refs/heads/main/Happy.csv

Read data from csv file
"""

# taking a look at columns avg_income and happyScore

# write a function that grabs the masses and distances as a list []
# Call the file using URL

import urllib.request
u = urllib.request.urlopen("https://raw.githubusercontent.com/ProfHan/ITEC4700/refs/heads/main/Happy.csv")
data = u.read().decode('utf-8')
lines = data.split("\n")

income = []
happiness = []

for line in lines[1:]:
  cols = line.split(",")
  income.append(float(cols[4]))
  happiness.append(float(cols[8]))

print(income)
print(happiness)

"""Making a visual graph of income and happiness"""

import numpy as np
import matplotlib.pyplot as plt

income = np.array(income)
happiness = np.array(happiness)

plt.plot(income, happiness, "bo")
plt.xlabel("Income")
plt.ylabel("Happiness")
plt.show()

"""Fitting the happy data curve with linear regression"""

a, b = np.polyfit(income, happiness, 1)
predicted_happiness = a * income + b

plt.plot(income, happiness, "bo")
plt.plot(income, predicted_happiness)
plt.xlabel("Income")
plt.ylabel("Happiness")
plt.show()

np.corrcoef(income, happiness)

"""Do you find a linear correlation between income and happiness? Can you discover any other patterns?

No I do not find a linear correlation between income and happiness. The difference in happy scores start to slow down around 5,000 and seems to peak around 17,000. So it seems that you don't really need that much money to have happiness.
"""