# -*- coding: utf-8 -*-
"""sat_gap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-tbJBMWBPPvT6PsKqVAnyp5Y07MbIXy

#SAP and GAP correlation and Linear Regression

Instead of using my URL, please download the file and use your github account (use your URL).
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("https://raw.githubusercontent.com/Shianne1/Artificial_Intelligence_Course/refs/heads/main/Python1/GoogleColab/SAT_GPA.csv")
df.head()

"""Do you find a linear correlation between these two?    Show the graph (both the actual data and the regression line)"""

plt.scatter(df['SAT Score'], df.GPA)

plt.xlabel("SAT Score")
plt.ylabel("GPA")
plt.title("SAT Score vs GPA")
plt.show()

a, b = np.polyfit(df['SAT Score'], df.GPA, 1)
predicted_score = a * df['SAT Score'] + b

plt.plot(df['SAT Score'], df.GPA, "bo")
plt.plot(df['SAT Score'], predicted_score, color='red')
plt.xlabel("SAT Score")
plt.ylabel("GPA")
plt.title("SAT Score vs GPA")
plt.show()

df.corr()
# I do think that there is a correlation between SAT scores and GPA.

"""After you find the regression, test it using  ONE SAP score between 400 and 1600"""

print(a*1050 + b)

"""I also you to test is using random int between 400 and 1600 (print of course)"""

from random import randint
print(a*randint(400,1600) + b)

"""Can you discover any other patterns?

The line starts to top off around the 1200 score where anyone who got a 1200 or higher was around a 4.0 with their GPA.
"""